### PR TITLE
Towards a new visualea on PyQT5 and Python 3

### PR DESCRIPTION
**Pull request by pradal**

### CODE REVIEW

**Comment by baugetfa** [comment]
@pradal 

forgot some QtCore, changed qt.QtCore.SIGNAL to QtCore.pyqtSignal

And removed all import as:
`from openalea.vpltk.qt import qt`
`from openalea.vpltk.qt.QtGui import *`

**Comment by pradal** [comment]
I will replace the pyqtsignal with the native interface:
```python
    self.connect(self.savescut, QtCore.pyqtSignal("triggered()"), self.save_changes)
```
by
```python
self.savescut.triggered().connect(self.save_changes)
```

**Comment by baugetfa** [comment]
I got the visualea main window open with the python shell working with,  for example, very simple numpy functions. But to reach that, I commented some lines referenced with # F. Bauget 2023-01-18. Just to see .
This is pretty ugly but that marks at least three different points making problem.

**Comment by pradal** [comment]
@baugetfa : If you change the API (valueChanged to on_valueChanged), make it consistent:
```python
def valueChanged(self, ...):
```
into

```python
def on_value_changed(self, ...):
```
It may also (mainly from the gui_catalog) have implications on the code (see node.py)
Thanks

**Pull request merged**
